volumes:
  # Named volume used by oboo-db
  oboo-data:

services:
  # MariaDB
  oboo-db:
    container_name: oboo-db
    image: mariadb:lts # MariaDB 11.4 (LTS)
    restart: unless-stopped
    expose:
      - 3306
    # Set default charset to UTF8 and collation to utf8_unicode_ci
    # See: https://docs.djangoproject.com/en/5.1/ref/databases/#creating-your-database
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      interval: 3s
      retries: 10
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      timeout: 5s
    volumes:
      # MariaDB data volume
      - oboo-data:/var/lib/mysql:Z

  # Oboo API
  oboo-api:
    container_name: oboo-api
    build: .
    image: oboo-api:1.0
    restart: unless-stopped
    command: gunicorn oboo.wsgi --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      # Defines the timezone in the container
      TZ: 'Europe/Paris'
      # Set to 0 for production
      DEBUG: 0
      # Make sure to generate a new private key for production use
      # See: https://docs.djangoproject.com/en/5.0/topics/signing/
      SECRET_KEY: ${SECRET_KEY}
      # 10.0.2.2 is required to test from the Android Studio Emulator
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1] 10.0.2.2
      CSRF_TRUSTED_ORIGINS: http://localhost:8888 http://127.0.0.1:8888
      DB_ENGINE: ${DB_ENGINE}
      DB_HOST: oboo-db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Hyperplanning credentials
      HP_USERNAME: ${HP_USERNAME}
      HP_PASSWORD: ${HP_PASSWORD}
      # This is the default admin account, make sure to use secure credentials !
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
      # /!\ Important, setting this to true will DELETE all data in the database and load the initial data.
      # If you are deploying the application for the very first time, set this to true.
      # If you want to redeploy the application with existing data, set this to false.
      INITIAL_DEPLOY: ${INITIAL_DEPLOY}
    volumes:
      # The container will collect all static files and put them in /app/static, which is bound to ./oboo_api/static on the host
      # This will ensure that the static files for the admin app are collected
      - ./oboo_api/static:/app/static
    depends_on:
      oboo-db:
        condition: service_healthy

  # NGINX
  nginx:
    container_name: oboo-nginx
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "${OBOO_API_PORT}:80"
    volumes:
      # Config file
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      # Static files
      - ./oboo_api/static:/static:ro
    depends_on:
      - oboo-api
